### ISSUE TITLE
Game don't load after packed new subtitle.

### ISSUE THREAD

**Issue by Gine214** [Albeoris/Pulse#10]
For example, I edits subtitle in ev_hang_060 and pack it back to the game.

When I play to the point that subtitle should appear. The game stuck at loading page forever.

Ps. I really appreciate your works. Thanks a lot. :)

**Comment by rhadamants** [comment]
The tool is working very well to extract and insert text. You must're doing something wrong. If you are translating to a language which the game does not have the characters, it will be necessary to edit the fonts of the game with the characters of your language.

The post the edited file to analyze the problem.

**Comment by Gine214** [comment]
I tried fresh install and insert just "ddd" in sentence and pack it back but it still the same.

Other part like movie subtitles or review text. Program works well with that part even insert my language alphabets.

**Comment by rhadamants** [comment]
I'm with the full translation and had no problems with texts which do not appear or endless loading

**Comment by Gine214** [comment]
What is your game's version?

**Comment by rhadamants** [comment]
steam.

**Comment by Gine214** [comment]
Still unsolved for me, maybe fix in next update :)

**Comment by rhadamants** [comment]
I do not think so. Because it works perfectly.
To which language you want to translate?
Version you are using: Repack or Steam?
I send the file you are trying to change.

Try to use this in my translation.
https://mega.co.nz/#!6oQCzAQD!XJvePGabtlFEijxSLpn5mTQczho1yYLpdl55trfYsYo

Em encoding use "New"

**Comment by Gine214** [comment]
It does not works again. 

I try to translate using repack version. Because I'm not sure about ban system of steam.

Maybe there's problem with crack or something.

I will try again on steam. thx :)

**Comment by rhadamants** [comment]
You can record a video of how you are doing and send me?

**Comment by Gine214** [comment]
OK.

**Comment by Gine214** [comment]
http://1drv.ms/1ArsSo6

This is how I do.

**Comment by rhadamants** [comment]
https://www.youtube.com/watch?v=s0nAl39S9Jc
Using commit 32

**Comment by Gine214** [comment]
Yes I use latest commit but still stuck.

I don't have any problem in movie cutscenes but I think it about in game cutscene on the point I show you before.

In the opening movie, I can translate and show my subtitles perfectly well.

**Comment by Albeoris** [comment]
Hello. Unpack your file again (after packing).
If an error occurs, or the file's contents change, I need your files to determine the cause of the problem.

**Comment by Gine214** [comment]
It cannot unpack subtitle file after error occur.

unpack >>> insert text>>> pack >>> play >>> Forever loading >>> unpack again>>> nothing come out

**Comment by Albeoris** [comment]
Nice. Send me a link to the your repack (albeoris gmail.com)

**Comment by Gine214** [comment]
http://1drv.ms/1ArsSo6

I finish upload.

**Comment by Gine214** [comment]
For Your Information.

I've got same problem on steam version.

**Comment by Albeoris** [comment]
I have not forgotten about you guys. As part of the fix to this problem, I completely rewrote the mechanism of unpacking and packing. When I finished rework some parts, the problem should be resolved. Please wait.

**Comment by Gine214** [comment]
I will waiting for next update. Thanks. :)

Another question is how to use your translation program.

I don't know how to open it.

**Comment by Gine214** [comment]
Problem solve!
